### ISSUE TITLE
[Bug]: Error in `Fetch Contribution` script

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#1234]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

Running the script [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Fetch_Contributions) using the command: 

```
python3 fetch_contributions.py --username HarshCasper --organization scipy
```

gives me the following traceback:

```
Traceback (most recent call last):
  File "fetch_contributions.py", line 168, in <module>
    print(response.get_pullrequests())
  File "fetch_contributions.py", line 137, in get_pullrequests
    for repo in self._list_of_repositories():
  File "fetch_contributions.py", line 49, in _list_of_repositories
    return list(pd.Series(list(set(Repositories))).str.strip().values)
  File "/home/hmishra/Rotten-Scripts/env/lib/python3.6/site-packages/pandas/core/generic.py", line 5137, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/hmishra/Rotten-Scripts/env/lib/python3.6/site-packages/pandas/core/accessor.py", line 187, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/hmishra/Rotten-Scripts/env/lib/python3.6/site-packages/pandas/core/strings.py", line 2100, in __init__
    self._inferred_dtype = self._validate(data)
  File "/home/hmishra/Rotten-Scripts/env/lib/python3.6/site-packages/pandas/core/strings.py", line 2157, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!
```

 

### Expected Behavior

The expected behavior is: 

- Script should be able to fetch the repositories.
- Script should be able to fetch all our pull requests.
- Script should output them all neatly in a Markdown table.

### To Reproduce

Follow the setup instructions on the Script README and try it out. The `requirements.txt` file is buggy as well and most of the packages have to be manually installed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HarshCasper** [comment]
cc: @kadatatlukishore

**Comment by Zircoz** [comment]
@HarshCasper this issue is taken or it's open ?

**Comment by HarshCasper** [comment]
> @HarshCasper this issue is taken or it's open ?

Assigned you the same.

**Comment by Ankit1598** [comment]
Hey @HarshCasper I have already resolved this issue.
